version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - pytest  # Run tests
      - mkdir -p build
      - cp -r * build/

artifacts:
  files:
    - '**/*'
    - 'build/**/*'
